name: Update Homebrew Formula

on:
  push:
    tags:
      - "v*"

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update formula
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          VERSION=${{ steps.get_version.outputs.VERSION }}
          TARBALL_URL="https://github.com/${{ github.repository }}/archive/refs/tags/${VERSION}.tar.gz"
          TARBALL_SHA256=$(curl -sL $TARBALL_URL | shasum -a 256 | cut -d ' ' -f 1)

          # Update URL
          sed -i.bak 's|url ".*"|url "'"${TARBALL_URL}"'"|' Formula/tms.rb

          # Update SHA256
          sed -i.bak 's|sha256 ".*"|sha256 "'"${TARBALL_SHA256}"'"|' Formula/tms.rb

          # Update version assertion
          VERSION_WITHOUT_V="${VERSION#v}"
          sed -i.bak 's|assert_match "tms version .*"|assert_match "tms version '"${VERSION_WITHOUT_V}"'", shell_output("#{bin}/tms --version")|' Formula/tms.rb

          # Remove backup files
          rm Formula/tms.rb.bak

          git add Formula/tms.rb
          git commit -m "Update Homebrew formula to ${VERSION}"
          git push origin main

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
